  Level.create(number: 1, points: 1, image: 'level_1.png')
  Level.create(number: 2, points: 2, image: 'level_2.png')
  Level.create(number: 3, points: 3, image: 'level_3.png')
  Level.create(number: 4, points: 4, image: 'level_4.png')
  Level.create(number: 5, points: 5, image: 'level_5.png')
  Level.create(number: 6, points: 6, image: 'level_6.png')
